version: 2.1
orbs:
  newman: postman/newman@0.0.2
API-jobs:
  Specimen-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Specimen.postman_collection.json
          environment: ./Testing.postman_environment.json
  

workflows:
  version: 2
  workflow:
    API-jobs:
      - Specimen-collection-run

      
    
      
