version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  Dna-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./DNA.postman_collection.json
          environment: ./Testing.postman_environment.json
  Specimen-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Specimen_final.postman_collection.json
          environment: ./Testing.postman_environment.json

workflows:
  version: 2
  workflow:
    jobs:
      - Specimen-collection-run 
      - Dna-collection-run:
          requires:
            - Specimen-collection-run
        
    
      
